version: 0.2

env:
  variables:
      EFS_DIR: "/opt/sonar"
      EFS_DNS: "fs-98eb7a50.efs.eu-west-1.amazonaws.com"
      DOCKER_CACHE_IMAGE_VERSION: "latest"
      
phases:
  pre_build:
    commands:
      - echo Pre-Build started on `date`
      - service docker start
      
      - echo demarrage de Sonar
      - usermod -u 1001 sonar
      - groupmod -g 1001 sonar
      - mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 $EFS_DNS:/ $EFS_DIR
      - echo Supression d un eventuel PID subsistant
      - rm -f /opt/sonar/sonarqube-7.3/bin/linux-x86-64/./SonarQube.pid
      - /opt/sonar/sonarqube-7.3/bin/linux-x86-64/sonar.sh start
      
      - echo Recuperation des metadonnees de l application
      - PACKAGE_VERSION=$(grep -m 1 '<version>' pom.xml | awk -F">" '{print $2}' | awk -F"<" '{print $1}')
      - APPLICATION_NAME=$(grep -m 1 '<artifactId>' pom.xml | awk -F">" '{print $2}' | awk -F"<" '{print $1}')
#      - PACKAGE_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
#      - APPLICATION_NAME=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='artifactId']/text()" pom.xml)
      
      - echo Recuperation de la precedente image de l application des maintenant pour gagner du temps dans la phase post-build
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - echo Si l'image cache n'existe pas elle est reconstruire, sinon elle est telechargee
      - chmod +x build-docker.sh
      - ./build-docker.sh $IMAGE_REPO_NAME $DOCKER_CACHE_IMAGE_VERSION dockerfile_basis $AWS_REGION $AWS_ACCOUNT_ID
 
  build:
    commands:
      - echo Build started on `date`
#      - export MAVEN_OPTS="-Dmaven.repo.local=/opt/sonar/sonarqube-7.3/cache"
      - mvn -T 1C -Dmaven.test.skip=true clean package
      - mvn -T 1C test
      - mvn dependency-check:check
      - timeout 60 sh -c 'until ps aux | grep [o]rg.sonar.ce.app.CeServer; do sleep 1; done'
      - mvn sonar:sonar #-Duser.home=/opt/sonar/sonarqube-7.3/cache/
      - echo Get project name and version from the pom.xml...
      - cp target/$APPLICATION_NAME-$PACKAGE_VERSION.jar .
      
  post_build:
    commands:
      - echo Post-Build started on `date`
      - echo Verification de la presence de l'image Docker cache en local
      - timeout 60 sh -c 'until docker images | grep $IMAGE_REPO_NAME | grep $DOCKER_CACHE_VERSION; do sleep 1; done'
      - docker build --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DOCKER_CACHE_VERSION --build-arg PACKAGE_VERSION=$PACKAGE_VERSION --build-arg APPLICATION_NAME=$APPLICATION_NAME -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PACKAGE_VERSION .
"      - docker tag $IMAGE_REPO_NAME:$PACKAGE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PACKAGE_VERSION
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PACKAGE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PACKAGE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PACKAGE_VERSION > imagedefinitions.json
      
      
cache:
  paths:
    - '/root/.m2/**/*'
    
artifacts:
    files: imagedefinitions.json